services:
  mysql:
    image: mysql:8.0.34
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM-ROOT-PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

